/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as StockRouteImport } from './routes/stock'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiPublicHooksAutoBackupRouteImport } from './routes/api/public/hooks/auto-backup'

const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutoBackupRoute =
  ApiPublicHooksAutoBackupRouteImport.update({
    id: '/api/public/hooks/auto-backup',
    path: '/api/public/hooks/auto-backup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/stock': typeof StockRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/violations': typeof ViolationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/stock': typeof StockRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/violations': typeof ViolationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/stock': typeof StockRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/violations': typeof ViolationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignments'
    | '/dashboard'
    | '/employees'
    | '/stock'
    | '/unauthorized'
    | '/violations'
    | '/admin/users'
    | '/api/public/hooks/auto-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignments'
    | '/dashboard'
    | '/employees'
    | '/stock'
    | '/unauthorized'
    | '/violations'
    | '/admin/users'
    | '/api/public/hooks/auto-backup'
  id:
    | '__root__'
    | '/'
    | '/assignments'
    | '/dashboard'
    | '/employees'
    | '/stock'
    | '/unauthorized'
    | '/violations'
    | '/admin/users'
    | '/api/public/hooks/auto-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentsRoute: typeof AssignmentsRoute
  DashboardRoute: typeof DashboardRoute
  EmployeesRoute: typeof EmployeesRoute
  StockRoute: typeof StockRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ViolationsRoute: typeof ViolationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiPublicHooksAutoBackupRoute: typeof ApiPublicHooksAutoBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-backup': {
      id: '/api/public/hooks/auto-backup'
      path: '/api/public/hooks/auto-backup'
      fullPath: '/api/public/hooks/auto-backup'
      preLoaderRoute: typeof ApiPublicHooksAutoBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentsRoute: AssignmentsRoute,
  DashboardRoute: DashboardRoute,
  EmployeesRoute: EmployeesRoute,
  StockRoute: StockRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ViolationsRoute: ViolationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiPublicHooksAutoBackupRoute: ApiPublicHooksAutoBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
