/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as StockRouteImport } from './routes/stock'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BulkMessagesRouteImport } from './routes/bulk-messages'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AssignmentDeductionsRouteImport } from './routes/assignment-deductions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPendingRouteImport } from './routes/admin/pending'
import { Route as AdminBackupsRouteImport } from './routes/admin/backups'
import { Route as ApiPublicHooksAutoBackupRouteImport } from './routes/api/public/hooks/auto-backup'

const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkMessagesRoute = BulkMessagesRouteImport.update({
  id: '/bulk-messages',
  path: '/bulk-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentDeductionsRoute = AssignmentDeductionsRouteImport.update({
  id: '/assignment-deductions',
  path: '/assignment-deductions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPendingRoute = AdminPendingRouteImport.update({
  id: '/admin/pending',
  path: '/admin/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBackupsRoute = AdminBackupsRouteImport.update({
  id: '/admin/backups',
  path: '/admin/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutoBackupRoute =
  ApiPublicHooksAutoBackupRouteImport.update({
    id: '/api/public/hooks/auto-backup',
    path: '/api/public/hooks/auto-backup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignment-deductions': typeof AssignmentDeductionsRoute
  '/assignments': typeof AssignmentsRoute
  '/bulk-messages': typeof BulkMessagesRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/stock': typeof StockRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/violations': typeof ViolationsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignment-deductions': typeof AssignmentDeductionsRoute
  '/assignments': typeof AssignmentsRoute
  '/bulk-messages': typeof BulkMessagesRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/stock': typeof StockRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/violations': typeof ViolationsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignment-deductions': typeof AssignmentDeductionsRoute
  '/assignments': typeof AssignmentsRoute
  '/bulk-messages': typeof BulkMessagesRoute
  '/dashboard': typeof DashboardRoute
  '/employees': typeof EmployeesRoute
  '/stock': typeof StockRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/violations': typeof ViolationsRoute
  '/admin/backups': typeof AdminBackupsRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/public/hooks/auto-backup': typeof ApiPublicHooksAutoBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignment-deductions'
    | '/assignments'
    | '/bulk-messages'
    | '/dashboard'
    | '/employees'
    | '/stock'
    | '/unauthorized'
    | '/violations'
    | '/admin/backups'
    | '/admin/pending'
    | '/admin/users'
    | '/api/public/hooks/auto-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignment-deductions'
    | '/assignments'
    | '/bulk-messages'
    | '/dashboard'
    | '/employees'
    | '/stock'
    | '/unauthorized'
    | '/violations'
    | '/admin/backups'
    | '/admin/pending'
    | '/admin/users'
    | '/api/public/hooks/auto-backup'
  id:
    | '__root__'
    | '/'
    | '/assignment-deductions'
    | '/assignments'
    | '/bulk-messages'
    | '/dashboard'
    | '/employees'
    | '/stock'
    | '/unauthorized'
    | '/violations'
    | '/admin/backups'
    | '/admin/pending'
    | '/admin/users'
    | '/api/public/hooks/auto-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentDeductionsRoute: typeof AssignmentDeductionsRoute
  AssignmentsRoute: typeof AssignmentsRoute
  BulkMessagesRoute: typeof BulkMessagesRoute
  DashboardRoute: typeof DashboardRoute
  EmployeesRoute: typeof EmployeesRoute
  StockRoute: typeof StockRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ViolationsRoute: typeof ViolationsRoute
  AdminBackupsRoute: typeof AdminBackupsRoute
  AdminPendingRoute: typeof AdminPendingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiPublicHooksAutoBackupRoute: typeof ApiPublicHooksAutoBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-messages': {
      id: '/bulk-messages'
      path: '/bulk-messages'
      fullPath: '/bulk-messages'
      preLoaderRoute: typeof BulkMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignment-deductions': {
      id: '/assignment-deductions'
      path: '/assignment-deductions'
      fullPath: '/assignment-deductions'
      preLoaderRoute: typeof AssignmentDeductionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pending': {
      id: '/admin/pending'
      path: '/admin/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AdminPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/backups': {
      id: '/admin/backups'
      path: '/admin/backups'
      fullPath: '/admin/backups'
      preLoaderRoute: typeof AdminBackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-backup': {
      id: '/api/public/hooks/auto-backup'
      path: '/api/public/hooks/auto-backup'
      fullPath: '/api/public/hooks/auto-backup'
      preLoaderRoute: typeof ApiPublicHooksAutoBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentDeductionsRoute: AssignmentDeductionsRoute,
  AssignmentsRoute: AssignmentsRoute,
  BulkMessagesRoute: BulkMessagesRoute,
  DashboardRoute: DashboardRoute,
  EmployeesRoute: EmployeesRoute,
  StockRoute: StockRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ViolationsRoute: ViolationsRoute,
  AdminBackupsRoute: AdminBackupsRoute,
  AdminPendingRoute: AdminPendingRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiPublicHooksAutoBackupRoute: ApiPublicHooksAutoBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
